name: GreatCompactors
version: "${project.version}"
main: io.github.greatericontop.greatcompactors.GreatCompactors
api-version: 1.21
authors: [greateric]

commands:
  givecompactor:
    description: Give a personal compactor to you
    usage: /givecompactor
    permission: greatcompactors.givecompactor

permissions:
  greatcompactors.givecompactor:
    description: Allows /givecompactor
    default: true
